// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddOutlay: typeof import('./src/fragments/AddOutlay.vue')['default']
    CreateBill: typeof import('./src/fragments/CreateBill.vue')['default']
    DeleteBill: typeof import('./src/fragments/DeleteBill.vue')['default']
    DeleteOutlay: typeof import('./src/fragments/DeleteOutlay.vue')['default']
    LeftMenu: typeof import('./src/fragments/LeftMenu.vue')['default']
    UpdateBill: typeof import('./src/fragments/UpdateBill.vue')['default']
    UpdateOutlay: typeof import('./src/fragments/UpdateOutlay.vue')['default']
  }
}
