// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddOutlay: typeof import('./src/fragments/Outlay/AddOutlay.vue')['default']
    CreateBill: typeof import('./src/fragments/Bill/CreateBill.vue')['default']
    DeleteBill: typeof import('./src/fragments/Bill/DeleteBill.vue')['default']
    DeleteOutlay: typeof import('./src/fragments/Outlay/DeleteOutlay.vue')['default']
    Main: typeof import('./src/fragments/Main.vue')['default']
    SideView: typeof import('./src/fragments/SideView.vue')['default']
    UpdateBill: typeof import('./src/fragments/Bill/UpdateBill.vue')['default']
    UpdateOutlay: typeof import('./src/fragments/Outlay/UpdateOutlay.vue')['default']
  }
}
